### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ddwy** [srmainwaring/curio_firmware#4]
1

**Comment by srmainwaring** [comment]
@ddwy how are you getting on running the rover? You can bring up various nodes independently to check that the component parts are working. It really helps to have `rqt` and `rviz` running so you can see what is online. If you need further help feel free to ask here.

**Comment by ddwy** [comment]
When I run the program, the following error occurs：

`roslaunch curio_bringup curio_robot.launch `

`INFO] [1605144733.663647]: Loading regressor from` `/home/ubuntu/curio_ws/src/curio/curio_base/data/lx16a_tree_regressor.joblib`
`[INFO] [1605144733.738443]: Starting control loop at 20.0 Hz`
`[ERROR] [1605144779.216669]: Lost sync with device, restarting...`
`[INFO] [1605144779.220181]: Requesting topics...`
`[ERROR] [1605144794.224024]: Lost sync with device, restarting...`


How to solve the above errors？

**Comment by ddwy** [comment]
How to confirm the communication between Arduino Mega 2560 and LewanSoul BusLinker LX-16A Bus Servo v2.4 ？

**Comment by ddwy** [comment]
The following command can be used to release data, but the wheel operation cannot be controlled normally：

`rosrun rqt_robot_steering rqt_robot_steering`
0.63 m/s , 0.95 rad/s

`rostopic echo /servo/command`
`wheel_commands: [533, 421, 517, -981, -963, -972]`
`steer_commands: [361, 625, 427, 564]`
`---`
`^Cheader: `
`  seq: 1451`
`  stamp: `
`    secs: 0`
`    nsecs:         0`
`  frame_id: ''`
`wheel_commands: [533, 421, 517, -981, -963, -972]`
`steer_commands: [361, 625, 427, 564]`
`---`

`rostopic echo /cmd_vel`
`linear: `
`  x: 0.63`
`  y: 0.0`
`  z: 0.0`
`angular:` 
`  x: 0.0`
`  y: 0.0`
`  z: 0.949`
`---`
`linear:` 
`  x: 0.63`
`  y: 0.0`
`  z: 0.0`
`angular:` 
`  x: 0.0`
`  y: 0.0`
`  z: 0.949`

How to solve this problem？

**Comment by srmainwaring** [comment]
@ddwy I think the issue you are seeing with ROS serial losing sync is connected to your question [The wheels of a car don't move #9](https://github.com/srmainwaring/curio/issues/9) about the hardware hookup.

In the curio repo there are a number of Python scripts that can help you test your servo hardware:

https://github.com/srmainwaring/curio/blob/master/curio_base/scripts/lx16a_driver_test.py

is a useful one to check the low level drivers are working. Put your rover on a stand and only connect one of the wheel servos as the test code will rotate the servo fully which would damage a steering unit. 

Once you've established you have power and control over the servos, work through the instructions for [curio_base](https://github.com/srmainwaring/curio#curio_base) and check the nodes are reporting the publications and subscriptions listed in the guide.

**Comment by srmainwaring** [comment]
@ddwy I'll close this issue on the basis that it was resolved in the discussion in  https://github.com/srmainwaring/curio/issues/9.
