### ISSUE TITLE
What do the parameters of this array represent

### ISSUE THREAD

**Issue by ddwy** [srmainwaring/curio_firmware#6]
What do the parameters of this array buf[] represent? 

void LobotSerialServoAngleAdjust(HardwareSerial &SerialX, uint8_t id, uint8_t deviation)
{
  byte buf[7];
  buf[0] = buf[1] = LOBOT_SERVO_FRAME_HEADER;
  buf[2] = id;
  buf[3] = 4;
  buf[4] = LOBOT_SERVO_ANGLE_OFFSET_ADJUST;
  buf[5] = deviation;
  buf[6] = LobotCheckSum(buf);
  SerialX.write(buf, 7);
}

**Comment by srmainwaring** [comment]
@ddwy the `buf[]` array contains the bytes of the serial message, in this case a message that is to be sent from the Arduino to the LX16A. The serial protocol for the LX16A is defined in the attached document [LewanSoul Bus Servo Communication Protocol.pdf](https://github.com/srmainwaring/curio_firmware/files/5552108/LewanSoul.Bus.Servo.Communication.Protocol.pdf) (also available from the LewanSoul download area: [LX-16A Bus Servo](https://www.dropbox.com/sh/b3v81sb9nwir16q/AACkK-tg0q39fKJZcSl-YrqOa/LX-16A%20Bus%20Servo)).

If you're not familiar with serial communication protocols it's worth placing print statements in the code so you can see what's going on and match the messages up to the specification. If you want to delve even deeper I can recommend getting yourself a logic analyser and software (I use [sigrok PulseView](https://sigrok.org/)) so you can examine the UART signals on the wire.
