### ISSUE TITLE
Mega 2560: how does it works Serial1 ?

### ISSUE THREAD

**Issue by ddwy** [srmainwaring/curio_firmware#7]
Mega 2560: how does it works Serial1 ?

**Comment by srmainwaring** [comment]
@ddwy your question is not an issue or question about the curio firmware, but a general question about how to use the multiple serial ports on an Arduino Mega 2560.

I'm happy to help you get the firmware running for your Sawppy rover as it is involved, but this question would be better directed to a forum focussed on getting familiar with Arduinos and their functionality. The [Arduino Serial Reference](https://www.arduino.cc/reference/en/language/functions/communication/serial/) is a good starting point.
